### ISSUE TITLE
Epic: Merge venus-messager to go-messenger

### ISSUE THREAD

**Issue by Fatman13** [ipfs-force-community/venus-messager#40]
As proposed by @steven004 in this [comment](https://github.com/filecoin-project/lotus/issues/5869#issuecomment-809199013). venus-messager could potentially be an alternative solution to various message related problems mentioned in [#5869](https://github.com/filecoin-project/lotus/issues/5869). In order to move this initiative forward, we may need to map out existing features venus-messager already offers, future roadmap, how venus-messager could be interacting with Lotus and etc in this thread before making a proposal to Lotus team. Hope to get everyone's valuable input on this.   

## Context

Due to volatilities in gas, sending/managing messages became problematic for miners/operators. As summarized by @raulk, current Lotus message management falls short on the following...

> (a) The base fee is a dynamically changing value and it directly determines whether pending messages will be included or not.
> (b) The max gas fee cap is a statically configured value in Lotus configuration, and by default Lotus ships with a value that might be considered too low in a large number of cases.
> (c) Messages from a given sender are ordered by nonce. A failure to include pending message 1 will prevent pending messages 2, 3, etc. from being included. This is the head-of-line blocking problem.

On the one hand, Lotus team is tight in resources to work on message optimizations. On the other hand, miners like @f8-ptrk shows concerns that changing existing logic might [break current status quo](https://github.com/filecoin-project/lotus/issues/5333#issuecomment-759782075) and turn out to be unfavorable. Given the above, venus-messager could be perfect alternative solution giving flexibility while allowing miners/operators have the ability of reverting back to Lotus any time they want.  

##  Related Issues

- [EPIC] Local Mpool Management: [#5333](https://github.com/filecoin-project/lotus/issues/5333)
- Set message fees interactively: [#5422](https://github.com/filecoin-project/lotus/issues/5422)
- mpool: messages stuck if have incorrect/stalled fee configuration: [#5192](https://github.com/filecoin-project/lotus/issues/5192)
- Log message execution error: [#5423](https://github.com/filecoin-project/lotus/issues/5423)
- Mpool monitoring tool for checking message selection: [#5424](https://github.com/filecoin-project/lotus/issues/5424)
- GasPrice and GasLimit have global policies/configs: [#2759](https://github.com/filecoin-project/lotus/issues/2759)

_Compiled by @raulk_

## Solution

To be Completed...

## Work

- [ ] Map out existing venus-messager features
- [ ] Docs on how venus-messager is addressing some of the current issues
- [ ] Roadmap on addressing remaining issues
- [ ] How Lotus can interact with venus-messager
- [ ] Merge venus-messager to go-messenger

**Comment by hunjixin** [comment]
problem a, c has been resolved in the current implementation of messager. question b still needs to be discussed carefully, and there are many ambiguous aspects. specifically issue  [#5333](https://github.com/filecoin-project/lotus/issues/5333),[#5422](https://github.com/filecoin-project/lotus/issues/5422),[#5423](https://github.com/filecoin-project/lotus/issues/5423),[#2759](https://github.com/filecoin-project/lotus/issues/2759),[#5192](https://github.com/filecoin-project/lotus/issues/5192)

**Comment by Fatman13** [comment]
@hunjixin Could you please elaborate a little more on how messager is addressing (a) and (c)? Thank you!

**Comment by hunjixin** [comment]
@Fatman13 
对于问题a, 其产生的原因在于，当网络拥塞的时候，消息打包不及时，那么之前预估的gas值，在后来的网络环境下（basefee发生了变化）并不合理，这会导致消息gas值偏高（额外的消耗）或者gas值偏低（消息失败）。但是在我们的系统中，消息推送到系统中并不会立即预估gas而是在定时推送一定数量的消息，比如矿工发送了1000条消息，messager每次可能仅仅挑选10条推送出去，这样的好处在于，消息数量少，更容易被打包，另一方面是每次预估的gas结果更加贴近当前的网络环境。
对于问题c，可能并没有一个万全的结果，但是在我们系统中可以一定程度上缓解这个问题，还是按上面的例子，矿工发送了1000笔消息，我们挑选10条。在我们挑选消息的过程中将消息按照一定的顺序排列，在挑选的过程中，如果消息发生错误，那么系统会跳过出问题的交易，顺延到下一笔交易。 但是如果已经推送出去的消息发生错误，就只能具体问题具体处理了。

**Comment by Fatman13** [comment]
@hunjixin 感谢！🙏
我把@raulk的一些设想贴过来，请教下@hunjixin。

> 1. Introduce a node health check API to detect when the Lotus node is not in a healthy state and prevent message sending.
> [#5762](https://github.com/filecoin-project/lotus/issues/5762)

这个应该是发消息前，最简单的check，需不需要API来做，不清楚。但是messager现在是有检查链已经同步后，再发消息吗？

> Introduce an mpool-level healthcheck API to evaluate inclusion-ability of a give message, and to detect when pending messages from a given sender are stuck, and therefore new messages would be affected by head-of-line blocking.
> [#5763](https://github.com/filecoin-project/lotus/issues/5763)

这个他设想的api，不清楚有没有？侦测pending消息是否被卡。

> An interactive UI for message sending that outputs the check results (including errors), and allows the user to adjust the base fee dynamically, getting real-time feedback on message inclusion probability.

这个是不是没有必要？都是messager自己在计算？

> Detection of whether TTY is interactive or non-interactive.
> If interactive, the CLI will open the interactive mode automatically.
> If non-interactive, the CLI will behave like it behaves today (just submit the message).

同上。

> Inversion of control so that all CLI operations that send messages (e.g. send, msig, deal making, etc.) call back to the UI for fee adjustment.
> [#5765](https://github.com/filecoin-project/lotus/issues/5765)

这个issue看下来就是相当于filwallet里面构建消息的功能？能不能算messager已经实现了？

> Interactive message management UI to visualise all pending messages from a sender, getting healthcheck status, and opening the interactive message sending UI to enable replace-by-fee.

这个互动模式怎么看？要不要实现？

> CLI flag to override the max fee cap in non-interactive mode.
> issue pending

同上。

> Enabling external signing (aka Bring Your Own Signature).
> TBD if this is being solved here too.
> [#5122](https://github.com/filecoin-project/lotus/issues/5122)

这个filwallet已经实现了，可以算messager已经解决了吗？

感谢解答！🙏

**Comment by hunjixin** [comment]
对于#5762 ，检查链是否完全同步并不是必须的，messager系统对同步是否及时并不敏感。对于比较小的延迟没有什么影响，对于大的同延迟这应该是节点集群应该考虑的事情。我们通过一些巧妙的办法保证同步延迟上半天也可以正常的更新已有消息的状态，这么长时间应该足够节点解决问题了。

对于#5763， 目前没有做相关的工作，。不过在messager里面是可以实现这个功能，因为我们掌握所有自己的消息，可以通过一些时间比较来判断该地址消息是否延迟的太久。这样可以通过一些更积极的手段（外部系统，邮件等）来告知运维人员处理问题。这个问题会列入到我们的需求里面。

交互式命令行个人觉得有点鸡肋，在意basefee的用户通常是矿工，因为他们有大量的消息需要发送，在这种情况下，矿工不太可能24小时值守，一条一条消息的设置basefee。对于一般用户来说，发送的消息少，并不会太关注basefee的损耗。

#5763 并非是filwallet构建消息，而是保存消息原型，在真正推送的时候确定gas参数，签名等信息。这个我们是实现了的，不过并非通过交互是命令行来实现，而是通过一系列的配置策略来控制。UI方面，因为我们是基于sql开发的，未来甚至可以提供web版本界面管理工具，这样不是更好么。

#5122 已经实现了，只要钱包实现了我们的协议，messager系统都可以接入。

**Comment by Fatman13** [comment]
@hunjixin 感谢！

> 在我们挑选消息的过程中将消息按照一定的顺序排列

这个顺序是不是优先像winningPost，windowPost这种相对比较重要的消息？是在配置文件中可以配置的吗？

**Comment by Fatman13** [comment]
> 我们通过一些巧妙的办法保证同步延迟上半天也可以正常的更新已有消息的状态

链不同步的话，不知道当前网络的gas情况，也可以预估出消息比较准确的gas费吗？@hunjixin

**Comment by hunjixin** [comment]
> @hunjixin 感谢！
> 
> > 在我们挑选消息的过程中将消息按照一定的顺序排列
> 
> 这个顺序是不是优先像winningPost，windowPost这种相对比较重要的消息？是在配置文件中可以配置的吗？

是的, 设计中，这种类型的消息会优先打包

**Comment by hunjixin** [comment]
> > 我们通过一些巧妙的办法保证同步延迟上半天也可以正常的更新已有消息的状态
> 
> 链不同步的话，不知道当前网络的gas情况，也可以预估出消息比较准确的gas费吗？@hunjixin
链是要同步的，我意思是这个保证应该是节点服务来保证。messager落后一两个没什么大影响。

**Comment by Fatman13** [comment]
@hunjixin，@vyzo那边好像推了一个些新的mpool相关的api。https://github.com/filecoin-project/lotus/pull/5822

**Comment by Fatman13** [comment]
@hunjixin 再请教下，@raulk在https://github.com/protocol/web3-dev-team/pull/48里面提到的以下流程，是不是`venus`已经实现了？

> The way to perform external signing is:
> 
> Client calls a method that returns a message prototype.
> Client obtains a nonce through JSON-RPC. This is not automatic because the API doesn't know if the client is batching messages or sending a one off.
> Client obtains a gas estimate.
> Client fills in the nonce and gas estimate in the message prototype, and creates a message payload.
> Client signs the message payload with a self-provided signature.
> Client invokes MpoolPush to push the signed message.
> We believe that the delta between the status quo and seamless external message signing would be as follows (in order of priority):
> 
> To create an example go app demoing external signing implementing the flow above. It can serve as a reference for other implementors / users. Right now we can only do this for raw messages (e.g. transfer) and multisig messages.
> Migrate markets JSON-RPCs to message prototypes.
> Migrate deal making JSON-RPCs to message prototypes.
> Migrate payment channel JSON-RPCs to message prototypes.

**Comment by hunjixin** [comment]
第一步构造原型是没有的，但是我觉得这里是可以客户端自己来完成的，所需要的可能是一个好用的消息构造库。 而后续的获取nonce，预估gas，签名，发送等流程在messager中都是自动完成的。并不需要在客户端和节点之间反复请求。
